<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.4.6" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>InvoiceManager.AppHost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.Azure.CosmosDB" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.Azure.Functions" Version="13.4.6" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.62.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InvoiceManager.AdminWeb\InvoiceManager.AdminWeb.csproj" />
    <ProjectReference Include="..\InvoiceManager.Functions\InvoiceManager.Functions.csproj" />
    <ProjectReference Include="..\..\tools\InvoiceManager.Seeder\InvoiceManager.Seeder.csproj" />
  </ItemGroup>

</Project>
